In [1]:
import numpy as np

In [46]:
A = np.array(
   [[1,3,8],
    [1,2,6],
    [0,1,2]]
)
C = np.array(
    [ [1,3],
    [1,2],
    [0,1]
    ]
)
R = np.array(
   [
       [1,0,2],
       [0,1,2]
   ]
)

In [47]:
C @ R

array([[1, 3, 8],
       [1, 2, 6],
       [0, 1, 2]])

In [73]:
C1 = np.array(
   [
       [1,1],
       [0,1],
       [0,9]
   ]
)

In [65]:
R1 = np.array(
   [
     [1, 3, 8],
     [1, 2, 6]
   ]
)

In [77]:
C1 = C

In [67]:
np.linalg.inv(C1.T @ C1)

array([[ 4.66666667, -1.66666667],
       [-1.66666667,  0.66666667]])

In [68]:
R = R1

In [69]:
np.linalg.inv((R @ R.T))

array([[ 4.55555556, -6.11111111],
       [-6.11111111,  8.22222222]])

In [78]:
M = np.linalg.inv(C1.T @ C1) @ (C1.T @ A @ R.T) @ np.linalg.inv((R @ R.T))

In [79]:
M

array([[-2.,  3.],
       [ 1., -1.]])

In [80]:
C1 @ M @ R

array([[1.00000000e+00, 3.00000000e+00, 8.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 6.00000000e+00],
       [1.26565425e-14, 1.00000000e+00, 2.00000000e+00]])

In [81]:
M @ R

array([[ 1.00000000e+00, -2.57571742e-14,  2.00000000e+00],
       [ 1.26565425e-14,  1.00000000e+00,  2.00000000e+00]])

In [82]:
M

array([[-2.,  3.],
       [ 1., -1.]])

In [113]:
def decompose(mat,i,j):
    m,n = mat.shape
    first_val = mat[i][j]
    col = np.zeros((m,1))
    row = mat[i].reshape((1,n))
    for k in range(i,m):
        col[k] = mat[k][j] / first_val
    return col,row
    

In [121]:
mat = np.array(
   [[1,2,3],
    [4,5,6],
    [7,8,19]]
)

In [115]:
decompose(mat,0,0)

(array([[1.],
        [4.],
        [7.]]),
 array([[1, 2, 3]]))

In [122]:
tmp = mat
cols = []
rows = []

In [123]:
for i in range(min(mat.shape)):
    col,row = decompose(tmp,i,i)
    tmp = tmp - col @ row
    cols.append(col)
    rows.append(row)

In [126]:
print(np.concatenate(cols,axis=1))

[[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]


In [125]:
print(rows)

[array([[1, 2, 3]]), array([[ 0., -3., -6.]]), array([[ 0.,  0., 10.]])]


In [128]:
print(np.concatenate(rows,axis=0))

[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0. 10.]]


In [129]:
L = np.concatenate(cols,axis=1)

In [130]:
U = np.concatenate(rows,axis=0)

In [131]:
L @ U

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 19.]])

In [132]:
def f(mat):
    tmp = mat
    cols = []
    rows = []
    for i in range(min(mat.shape)):
        col,row = decompose(tmp,i,i)
        tmp = tmp - col @ row
        cols.append(col)
        rows.append(row)
    L = np.concatenate(cols,axis=1)
    U = np.concatenate(rows,axis=0)
    return L,U

In [133]:
f(mat)

(array([[1., 0., 0.],
        [4., 1., 0.],
        [7., 2., 1.]]),
 array([[ 1.,  2.,  3.],
        [ 0., -3., -6.],
        [ 0.,  0., 10.]]))

In [134]:
mat = np.array(
   [
       [9,0,0],
       [0,1,2],
       [0,2,8]
   ]
)

In [136]:
L,U = f(mat)

In [146]:
L,U

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 2., 1.]]),
 array([[9., 0., 0.],
        [0., 1., 2.],
        [0., 0., 4.]]))

In [138]:
L.T

array([[1., 0., 0.],
       [0., 1., 2.],
       [0., 0., 1.]])

In [143]:
D = np.array(
   [
       [9,0,0],
       [0,1,0],
       [0,0,4]
   ]
)

In [144]:
D @ L.T

array([[9., 0., 0.],
       [0., 1., 2.],
       [0., 0., 4.]])

In [149]:
mat = np.array(
   [
       [1,1,2],
       [1,2,2],
       [1,2,7]
   ]
)

In [150]:
L,U = f(mat)

In [151]:
L,U

(array([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]]),
 array([[1., 1., 2.],
        [0., 1., 0.],
        [0., 0., 5.]]))

In [152]:
def diag(mat):
    ans = np.zeros(mat.shape)
    for i in range(mat.shape[0]):
        ans[i][i] = mat[i][i]
    return ans

In [154]:
L @ diag(U) @ L.T

array([[1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 7.]])