In [92]:
import numpy as np

In [93]:
mat = np.array(
[
    [1,2,3.0],
    [1,5,7],
    [7,8,9]
])

In [94]:
mat

array([[1., 2., 3.],
       [1., 5., 7.],
       [7., 8., 9.]])

In [95]:
m,n = mat.shape

In [96]:
m,n

(3, 3)

In [97]:
Q = np.zeros((m,n))

In [98]:
for j in range(n):
    print(mat[:,j])
    print('-')

[1. 1. 7.]
-
[2. 5. 8.]
-
[3. 7. 9.]
-


In [99]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1 @ a2

32

In [100]:
def make_q(Q,a):
    if Q is not None:
        a -= Q @ Q.T @ a
    a = a / ((a ** 2).sum()**0.5)
    if Q is None:
        Q = a.reshape(-1,1)
    else:
        Q = np.concatenate([Q,a],axis=1)
    return Q,a

In [101]:
Q = None
for j in range(n):
    a = mat[:,j].reshape(-1,1).copy()
    Q,a = make_q(Q,a)
    print(Q,a)

[[0.14002801]
 [0.14002801]
 [0.98019606]] [[0.14002801]
 [0.14002801]
 [0.98019606]]
[[ 0.14002801  0.19629491]
 [ 0.14002801  0.96637494]
 [ 0.98019606 -0.16609569]] [[ 0.19629491]
 [ 0.96637494]
 [-0.16609569]]
[[ 0.14002801  0.19629491  0.97049496]
 [ 0.14002801  0.96637494 -0.21566555]
 [ 0.98019606 -0.16609569 -0.10783277]] [[ 0.97049496]
 [-0.21566555]
 [-0.10783277]]


In [102]:
mat

array([[1., 2., 3.],
       [1., 5., 7.],
       [7., 8., 9.]])

In [103]:
Q.T @ Q

array([[ 1.00000000e+00,  1.25900620e-16, -5.78237895e-16],
       [ 1.25900620e-16,  1.00000000e+00, -2.39405306e-15],
       [-5.78237895e-16, -2.39405306e-15,  1.00000000e+00]])

In [104]:
R = Q.T @ mat

In [105]:
R[np.abs(R < 0.00001)] = 0

In [106]:
R

array([[ 7.14142843,  8.82176453, 10.22204461],
       [ 0.        ,  3.89569899,  5.85864809],
       [ 0.        ,  0.        ,  0.43133109]])

In [107]:
Q @ R

array([[1., 2., 3.],
       [1., 5., 7.],
       [7., 8., 9.]])

In [108]:
Q.T @ Q

array([[ 1.00000000e+00,  1.25900620e-16, -5.78237895e-16],
       [ 1.25900620e-16,  1.00000000e+00, -2.39405306e-15],
       [-5.78237895e-16, -2.39405306e-15,  1.00000000e+00]])

In [109]:
R = Q.T @ mat

In [110]:
R

array([[ 7.14142843e+00,  8.82176453e+00,  1.02220446e+01],
       [ 8.88178420e-16,  3.89569899e+00,  5.85864809e+00],
       [-4.06619183e-15, -1.45439216e-14,  4.31331093e-01]])

In [111]:
Q.T @ Q @ mat

array([[1., 2., 3.],
       [1., 5., 7.],
       [7., 8., 9.]])

In [112]:
X = Q.T @ Q

In [113]:
X[np.abs(X)<0.0000000001] = 0

In [114]:
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
X @ mat

array([[1., 2., 3.],
       [1., 5., 7.],
       [7., 8., 9.]])

In [116]:
R

array([[ 7.14142843e+00,  8.82176453e+00,  1.02220446e+01],
       [ 8.88178420e-16,  3.89569899e+00,  5.85864809e+00],
       [-4.06619183e-15, -1.45439216e-14,  4.31331093e-01]])

In [117]:
R[np.abs(R) < 0.000001] = 0

In [118]:
R

array([[ 7.14142843,  8.82176453, 10.22204461],
       [ 0.        ,  3.89569899,  5.85864809],
       [ 0.        ,  0.        ,  0.43133109]])