In [104]:
import numpy as np

In [164]:
A = np.array(
     [
         [1,2],
         [3,4],
         [5,6]
     ]
)

In [165]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [181]:
u = np.array([
    [0,1],
    [1,1],
    [2,1]
])

In [182]:
v = np.array(
   [[0.1,0],
    [0,2]
   ]
)

In [209]:
u = np.random.randn(3,1)
u

array([[ 1.65094287],
       [-0.53807711],
       [ 1.03422699]])

In [210]:
v = np.random.randn(1,2)
v

array([[-0.37906489,  0.42610338]])

In [211]:
xx=(u.T ** 2).sum(axis=1,keepdims=True)

In [212]:
xx

array([[4.08476481]])

In [213]:
(u.T @ A) / xx

array([[1.27494403, 1.80057839]])

In [214]:
u.shape

(3, 1)

In [215]:
v.shape

(1, 2)

In [216]:
u @ v

array([[-0.62581448,  0.70347234],
       [ 0.20396614, -0.22927648],
       [-0.39203914,  0.44068762]])

In [217]:
for i in range(100):
    loss = ((A - u@v)**2).sum()
    if i % 2 == 0:
        v = (u.T @ A) / (u.T ** 2).sum(axis=1,keepdims=True)
    else:
        u = ((v @ A.T) / (v ** 2).sum(axis=1,keepdims=True)).T
    print(loss)

90.00888181632516
71.11714252481985
0.5102900090577672
0.2652235265468562
0.2645071816209503
0.2645050933711206
0.2645050872836162
0.26450508726587046
0.2645050872658191
0.2645050872658186
0.2645050872658187
0.26450508726581873
0.2645050872658186
0.2645050872658187
0.2645050872658188
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.26450508726581873
0.2645050872658

In [218]:
u 

array([[0.99102725],
       [2.26252611],
       [3.53402497]])

In [219]:
v

array([[1.36891108, 1.73402129]])

In [220]:
u @ v

array([[1.35662819, 1.71846235],
       [3.09719707, 3.92326845],
       [4.83776596, 6.12807454]])

In [193]:
u @ v

array([[ 2.71325637,  3.4369247 ],
       [ 6.19439414,  7.84653689],
       [ 9.67553191, 12.25614908]])

In [130]:
v

array([[20.77661898, 29.48212435],
       [20.77661898, 29.48212435]])

In [131]:
uu,sigama,vv = np.linalg.svd(A)

In [132]:
uu

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [133]:
sigama

array([5.4649857 , 0.36596619])

In [73]:
vv

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])